feat: Update Ott DTO
TEAMOTTDEVELOPERS/cocoman_server pull request #116
Opened 2022-01-17 08:46 UTC by kindkiz

OTT 정보를 조금 더 추가했습니다.

Contents <-> Ott관계에서 Ott 측에서도 Contents Set을 만들어줬습니다.

요금제는 지금 String으로 간단히 구현되어 있고, 더 많은 정보제공을 위해서는 Rate Plan Table을 새로 만드는 것도 좋을 것 같아요.

Ott Controller에서 이름으로 OTT를 조회할 수 있습니다.

2022-01-19 13:57 UTC, celi1004 requested changes

2022-01-19 13:57 UTC, celi1004 commented on src/main/java/orangetaxiteam/cocoman/web/OttController.java
> +    }
name 대신에 id로 가져오는 걸로 수정!
-> 프론트가 OTT 목록 조회해서 id값 가지고 있고, 한 OTT 조회할 땐 그 id로 조회하는게 맞는 것 같음

 method도 findById로 (뭘로 가지고 오는건지 메소드에 나타나게) 고치면 좋을 것 같네염~!

2022-01-19 13:57 UTC, celi1004 commented on src/main/java/orangetaxiteam/cocoman/application/OttApplicationService.java
> +        name = new String(nameArr);
일단 ID로 가져오는걸로 수정하면 이 코드는 필요가 없을 것 같지만, 
만약 나중에 이런 기능이 필요하면 enum 클래스나 value 타입을 활용하는게 좋을 것 같습니다~
데이터 상태변화 같은건 도메인단에 들어가도록!!

2022-01-19 13:57 UTC, celi1004 commented on src/main/java/orangetaxiteam/cocoman/application/dto/OttCreateRequestDTO.java
> +    private Set<Contents> contentsSet;
create하는데 contents들을 넣나?? ott가 생긴 다음에 contents에 ott를 넣지 않을까

2022-01-19 13:57 UTC, celi1004 commented on src/main/java/orangetaxiteam/cocoman/config/InitDummyData.java
> +import orangetaxiteam.cocoman.domain.*;
"*"를 사용해 import하면 다른 패키지에 동일한 클래스가 있을 수도 있고, 명확하지 않아서 실수할 여지가 있을 것 같습니다! 다 적어주는걸로 하죵

2022-01-19 13:57 UTC, celi1004 commented on src/main/java/orangetaxiteam/cocoman/web/OttController.java
> +import org.springframework.web.bind.annotation.*;
여기두//

2022-01-19 16:20 UTC, kindkiz commented on src/main/java/orangetaxiteam/cocoman/application/dto/OttCreateRequestDTO.java
> +    private Set<Contents> contentsSet;
ott와 contents는 1:N 관계가 아닌 M:N 관계이므로 생성의 전후 관계가 없는 것으로 생각했어. 
그래서 만약 ott를 생성할 때 들어갈 적절한 contents가 정해져 있지 않다면 빈 Set을 넣는 것을 의도했어.

반대 사례로는 Review를 보면 User와 1:N 관계니까 User가 먼저 생성된 뒤에야 Review를 만들 수 있어.

2022-01-19 16:20 UTC, kindkiz commented on src/main/java/orangetaxiteam/cocoman/web/OttController.java
> +import org.springframework.web.bind.annotation.*;
넹

2022-01-19 16:29 UTC, kindkiz commented on src/main/java/orangetaxiteam/cocoman/web/OttController.java
> +    }
id로 검색하는 것도 추가하되 이름으로 조회하는 것도 살리는 건 어때? 넷플릭스를 검색하고 싶을 땐, 넷플릭스를 치는게 직관적이잖아. 아직 프론트에서 어떻게 돌아가는지 몰라서 그러긴 한데 하나의 의견이야.

2022-01-19 16:39 UTC, kindkiz commented on src/main/java/orangetaxiteam/cocoman/web/OttController.java
> +    }
아 근데 해보니까 url이 겹쳐버리네 ㅠㅠ 그냥 id로 할게

2022-01-20 07:28 UTC, celi1004 requested changes

2022-01-20 07:28 UTC, celi1004 commented on src/main/java/orangetaxiteam/cocoman/application/OttApplicationService.java
> +        );
```suggestion
        return OttDTO.from(ott);
```

2022-01-20 07:28 UTC, celi1004 commented on src/main/java/orangetaxiteam/cocoman/application/dto/OttCreateRequestDTO.java
> +    private Set<Contents> contentsSet;
아 뭔가 사용할때를 생각해서 한 말이긴 한데 안바꿔도 될 것 같다!

2022-01-20 07:31 UTC, celi1004 commented on src/main/java/orangetaxiteam/cocoman/web/OttController.java
> +    }
지금 OTT 상세조회하는게 메인이나, 콘텐츠에 표시된 ott 아이콘을 클릭하는 경우인 듯 싶은데, 그땐 검색이 아니라 말그대로 조회니까 id(pk)로 조회하는게 맞는거같고! 
만약 나중에 검색기능이 필요하다면? /search/{name}이런식으로 만들면 될 것 같다~~

2022-01-20 10:31 UTC, celi1004 approved these changes

2022-01-21 09:18 UTC, merged