feat: add review create function
TEAMOTTDEVELOPERS/cocoman_server pull request #64
Opened 2021-02-14 11:23 UTC by celi1004

## Related Issue

Resolve : #*(Issue number)*

## Description

리뷰 등록 기능입니다
고친건 별로 없고.. 변수 이름이랑.. 조인컬럼..정도...

## Discussion

*(If you have any discussion about this work, write here)*

2021-02-15 05:08 UTC, GunHee5719 commented
그그 찾아보니깐 contents랑 content는 엄밀히 따지면 content가 맞긴 한 것 같은데..... 진영님이 결정해주세요ㅎㅎ 다만 수정하신다면 파일두 다 리팩 부탁드려요!

2021-02-15 05:18 UTC, GunHee5719 requested changes
이부분 해결되면 머지되어도 좋을 것 같습니다:)

2021-02-15 05:18 UTC, GunHee5719 commented on src/main/java/orangetaxiteam/cocoman/application/ReviewApplicationService.java
>                          "Invalid user id")
혹시 이부분, "Invalid user id" 가 맞긴 하지만, `errCode = 4000 (로그인 시 아이디 오류)` 와 혼동이 있을 수도 있을 것 같아서요. "Invalid user id on creating review" 와 같이 조금만 상세하게 해주시면 좋을 것 같아요.

아 그리구, ErrCode.ID_DOES_NOT_EXIST 관련해서 노션에 추가해주세요!

2021-02-15 05:18 UTC, GunHee5719 commented on src/main/java/orangetaxiteam/cocoman/application/ReviewApplicationService.java
>      @Autowired
생성자로 의존성을 주입받는 경우에는 Autowired 어노테이션을 생략해도 된다고 합니다! 제거해주셔도 될 것 같아요

2021-02-15 05:22 UTC, GunHee5719 commented on src/main/java/orangetaxiteam/cocoman/application/ReviewApplicationService.java
>                          "Invalid user id")
추가) Invalid user id는 다양한 위치에서 쓰이므로, 노션에서 하나하나 추가하실 필요는 없을 것 같아요. errMessage에 Invalid user id - [description] 방식으로 써도 될 것 같습니다.

그럼 4000번도 Invalid user id - signIn 이므로, 합쳐져도 괜찮지 않나 라고 생각합니다!

2021-02-20 13:24 UTC, celi1004 commented on src/main/java/orangetaxiteam/cocoman/application/ReviewApplicationService.java
>      @Autowired
> 이부분 해결되면 머지되어도 좋을 것 같습니다:)

수정했습니다!!

2021-02-20 19:28 UTC, hihiboss commented on src/main/java/orangetaxiteam/cocoman/application/ReviewApplicationService.java
>                          "Invalid user id")
이부분은 로그 찍을 때 앞에 어떤 메소드를 실행하는 부분에서 예외가 발생했는지 찍을 수 있기 때문에 따로 signin과 같은 표기는 필요없습니다!

@GunHee5719 @celi1004

2021-02-21 08:30 UTC, hihiboss approved these changes

2021-02-21 08:34 UTC, merged